apiVersion: kustomize.config.k8s.io/v1beta1
bases:
- ../../base
configMapGenerator:
- behavior: merge
  envs:
  - .env
  name: kanfer-test-configmap
kind: Kustomization
namePrefix: dev-
namespace: dev
patches:
- path: ingress-patch.yaml
  target:
    kind: Ingress
resources:
- namespace.yaml
