apiVersion: kustomize.config.k8s.io/v1beta1
commonLabels:
  app: kanfer-test
configMapGenerator:
- envs:
  - .env
  name: kanfer-test-configmap
generatorOptions:
  disableNameSuffixHash: true
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
