# This workflow will update tag/version, package and push a Docker container to the container registry.
# If configured to auto-deploy, it will also deploy the new version to the cluster.

name: Release

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
jobs:

  build:
    runs-on: ubuntu-latest
    env:
      IMAGE: "me-west1-docker.pkg.dev/koala-ops-demo-373407/koala-repo/kanfer-test"
      VERSION_FILE: VERSION
      DEPLOYMENT_FILE: deploy/base/deployment.yaml
    
    permissions:
      contents: 'write'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v3
    
    - name: Set current TAG as env variable
      run: echo "TAG=$(cat $VERSION_FILE | awk -F. '/[0-9]+\./{$NF++;print}' OFS=.)" >> $GITHUB_ENV
    - name: Echo current TAG
      run: echo "${{ env.TAG }}"
    - name: Change VERSION file with the new TAG
      run: echo $TAG > $VERSION_FILE

      # Authenticate to Google Cloud
      # TODO: generalize to other cloud providers
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: "1.20"
      
      # Build with goreleaser
    - name: GoReleaser release Action (build Docker image)
      uses: goreleaser/goreleaser-action@v4.2.0
      with:
        # Arguments to pass to GoReleaser
        args: release --clean --snapshot

      # Docker tag on just created image      
    - name: Docker tag image
      run: docker tag $IMAGE:latest $IMAGE:$TAG

      # TODO: generalize registry
      # Login to Docker registry
      # https://cloud.google.com/artifact-registry/docs/docker/authentication#json-key
      # https://github.com/docker/login-action#service-account-based-authentication-1
    - name: Login to Docker Image Registry
      uses: docker/login-action@v2
      with:
        registry: me-west1-docker.pkg.dev
        username: _json_key
        password: ${{ secrets.GCP_CREDENTIALS }}

      # Push to Docker registry
    - name: Push to Docker registry
      run: docker push $IMAGE:latest; docker push $IMAGE:$TAG

      # Bump version in VERSION file
    - name: Update VERSION file
      run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'CI@users.noreply.github.com'
          git add $VERSION_FILE
          git commit -m "Update VERSION to --> $TAG [skip ci]"
          git push origin main
          git tag $TAG
          git push origin --tags

  # Deploy the new version to the cluster
  deploy:
    uses: ./.github/workflows/deploy.yml
    needs: build
    permissions:
      contents: 'write'
      id-token: 'write'
    with:
      tag: $(cat VERSION | awk -F. '/[0-9]+\./{$NF++;print}' OFS=.)
      overlay: dev
      cluster_name: koala-demo-cluster
      cluster_zone: me-west1-a
    secrets: inherit